# Generated by Django 4.2.23 on 2025-07-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='cv',
            field=models.FileField(upload_to='media/cvs/'),
        ),
        migrations.AlterField(
            model_name='photosentreprise',
            name='image',
            field=models.ImageField(upload_to='media/photos_entreprise/'),
        ),
    ]
